=== n-dobryukha/Curriculum-Viewer/Report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="Report"
	xmlns:rep="Report"
	elementFormDefault="qualified">

	<!-- ROOT ELEMENT -->
	<xsd:element name="StudentReport">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="rep:Tasks"/>
				<xsd:element ref="rep:Courses"/>
				<xsd:element ref="rep:Programs"/>
				<xsd:element ref="rep:Students"/>
				<xsd:element ref="rep:Reports"/>
			</xsd:sequence>
		</xsd:complexType>

		<xsd:keyref name="keyRefTheoreticalTaskIdInCourses" refer="rep:keyTheoreticalTaskId">
			<xsd:selector xpath="rep:Courses/rep:Course/rep:Tasks/rep:Theoretical/rep:Task"/>
			<xsd:field xpath="@id"/>
		</xsd:keyref>

		<xsd:keyref name="keyRefTheoreticalTaskIdInReports" refer="rep:keyTheoreticalTaskId">
			<xsd:selector xpath="rep:Reports/rep:Report/rep:Tasks/rep:Theoretical/rep:Task"/>
			<xsd:field xpath="@id"/>
		</xsd:keyref>

		<xsd:keyref name="keyRefPracticalTaskIdInCourses" refer="rep:keyPracticalTaskId">
			<xsd:selector xpath="rep:Courses/rep:Course/rep:Tasks/rep:Practical/rep:Task"/>
			<xsd:field xpath="@id"/>
		</xsd:keyref>

		<xsd:keyref name="keyRefPracticalTaskIdInReports" refer="rep:keyPracticalTaskId">
			<xsd:selector xpath="rep:Reports/rep:Report/rep:Tasks/rep:Practical/rep:Task"/>
			<xsd:field xpath="@id"/>
		</xsd:keyref>

		<xsd:keyref name="keyRefCourseId" refer="rep:keyCourseId">
			<xsd:selector xpath="rep:Programs/rep:Program/rep:Courses/rep:Course"/>
			<xsd:field xpath="@id"/>
		</xsd:keyref>

		<xsd:keyref name="keyRefProgramId" refer="rep:keyProgramId">
			<xsd:selector xpath="rep:Students/rep:Student/rep:Program"/>
			<xsd:field xpath="@id"/>
		</xsd:keyref>

		<xsd:keyref name="keyRefStudentId" refer="rep:keyStudentId">
			<xsd:selector xpath="rep:Reports/rep:Report"/>
			<xsd:field xpath="@studentId"/>
		</xsd:keyref>
	</xsd:element>

	<!-- ELEMENTS -->
	<!-- Tasks -->
	<xsd:element name="Tasks" type="rep:TasksListType">
		<xsd:key name="keyTheoreticalTaskId">
			<xsd:selector xpath="rep:Theoretical/rep:Task"/>
			<xsd:field xpath="@id"/>
		</xsd:key>
		<xsd:key name="keyPracticalTaskId">
			<xsd:selector xpath="rep:Practical/rep:Task"/>
			<xsd:field xpath="@id"/>
		</xsd:key>
	</xsd:element>
	<!-- Courses -->
	<xsd:element name="Courses" type="rep:CoursesListType">
		<xsd:key name="keyCourseId">
			<xsd:selector xpath="rep:Course"/>
			<xsd:field xpath="@id"/>
		</xsd:key>

		<xsd:unique name="uniqueTasksInCourse">
			<xsd:selector xpath="rep:Course/rep:Tasks/rep:Task"/>
			<xsd:field xpath="@id"/>
		</xsd:unique>
	</xsd:element>
	<!-- Programs -->
	<xsd:element name="Programs" type="rep:ProgramsListType">
		<xsd:key name="keyProgramId">
			<xsd:selector xpath="rep:Program"/>
			<xsd:field xpath="@id"/>
		</xsd:key>
	</xsd:element>
	<!-- Students -->
	<xsd:element name="Students" type="rep:StudentsListType">
		<xsd:key name="keyStudentId">
			<xsd:selector xpath="rep:Student"/>
			<xsd:field xpath="@id"/>
		</xsd:key>

		<xsd:unique name="uniqueStudents">
			<xsd:selector xpath="rep:Student"/>
			<xsd:field xpath="rep:FullName"/>
			<xsd:field xpath="rep:City"/>
			<xsd:field xpath="rep:Email"/>
		</xsd:unique>

	</xsd:element>
	<!-- Reports -->
	<xsd:element name="Reports" type="rep:ReportItemsListType">
		<xsd:unique name="uniqueStudentInReport">
			<xsd:selector xpath="rep:Report"/>
			<xsd:field xpath="@studentId"/>
		</xsd:unique>
	</xsd:element>

	<!-- TYPES -->

	<xsd:simpleType name="StringType">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>

	<!-- BaseIdentifiable Type -->
	<xsd:complexType name="BaseIdentifiableType">
		<xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>

	<!-- Task Type -->
	<xsd:complexType name="TaskType">
		<xsd:complexContent>
			<xsd:extension base="rep:BaseIdentifiableType">
				<xsd:sequence>
					<xsd:element name="Name" type="rep:StringType"/>
					<xsd:element name="Duration" type="xsd:int"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="TaskItemsList">
		<xsd:sequence>
			<xsd:element name="Task" type="rep:TaskType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- TasksList Type -->
	<xsd:complexType name="TasksListType">
		<xsd:sequence>
			<xsd:element name="Theoretical" type="rep:TaskItemsList" minOccurs="0"/>
			<xsd:element name="Practical" type="rep:TaskItemsList" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- PropertyGroup Type -->
	<xsd:group name="PropertyGroup">
		<xsd:sequence>
			<xsd:element name="Name" type="rep:StringType"/>
			<xsd:element name="Author" type="rep:StringType"/>
			<xsd:element name="CreationDate" type="xsd:date"/>
		</xsd:sequence>
	</xsd:group>

	<!-- BaseTasksList Type -->
	<xsd:complexType name="BaseTasksListType">
		<xsd:sequence>
			<xsd:element name="Task" type="rep:BaseIdentifiableType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- Course Type -->
	<xsd:complexType name="CourseType">
		<xsd:complexContent>
			<xsd:extension base="rep:BaseIdentifiableType">
				<xsd:sequence>
					<xsd:group ref="rep:PropertyGroup" />
					<xsd:element name="Tasks">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="Theoretical" type="rep:BaseTasksListType" minOccurs="0"/>
								<xsd:element name="Practical" type="rep:BaseTasksListType" minOccurs="0"/>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- CoursesList Type -->
	<xsd:complexType name="CoursesListType">
		<xsd:sequence>
			<xsd:element name="Course" type="rep:CourseType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- Program Type -->
	<xsd:complexType name="ProgramType">
		<xsd:complexContent>
			<xsd:extension base="rep:BaseIdentifiableType">
				<xsd:sequence>
					<xsd:group ref="rep:PropertyGroup"/>
					<xsd:element name="Courses">
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="Course" type="rep:BaseIdentifiableType" maxOccurs="unbounded"/>
							</xsd:sequence>
						</xsd:complexType>
						<!-- Unique courses in Program -->
						<xsd:unique name="uniqueCoursesInProgram">
							<xsd:selector xpath="rep:Course"/>
							<xsd:field xpath="@id"/>
						</xsd:unique>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- ProgramsList Type -->
	<xsd:complexType name="ProgramsListType">
		<xsd:sequence>
			<xsd:element name="Program" type="rep:ProgramType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<!-- Email Type -->
	<xsd:simpleType name="EmailType">
		<xsd:restriction base="rep:StringType">
			<xsd:pattern value="[a-zA-Z0-9_\.]+@([a-zA-Z0-9_]+\.)+[a-zA-Z0-9]{2,3}">
			</xsd:pattern>
		</xsd:restriction>
	</xsd:simpleType>

	<!-- Student Type -->
	<xsd:complexType name="StudentType">
		<xsd:complexContent>
			<xsd:extension base="rep:BaseIdentifiableType">
				<xsd:sequence>
					<xsd:element name="FullName" type="rep:StringType"/>
					<xsd:element name="City" type="rep:StringType"/>
					<xsd:element name="Email" type="rep:EmailType"/>
					<xsd:element name="StartDate" type="xsd:date"/>
					<xsd:element name="IsSigned" type="xsd:boolean"/>
					<xsd:element name="Program" type="rep:BaseIdentifiableType"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- StudentsList Type -->
	<xsd:complexType name="StudentsListType">
		<xsd:sequence>
			<xsd:element name="Student" type="rep:StudentType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="TheoreticalTaskStatusType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Not started"/>
			<xsd:enumeration value="In progress"/>
			<xsd:enumeration value="Finished"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="PracticalTaskStatusType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Not started"/>
			<xsd:enumeration value="In progress"/>
			<xsd:enumeration value="Verifying"/>
			<xsd:enumeration value="Accepted"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="TaskRateType">
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="5"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="TaskItemForReportType">
		<xsd:complexContent>
			<xsd:extension base="rep:BaseIdentifiableType">
				<xsd:sequence>
					<xsd:element name="Rate" type="rep:TaskRateType" minOccurs="0"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="TheoreticalTaskItemForReportType">
		<xsd:complexContent>
			<xsd:extension base="rep:TaskItemForReportType">
				<xsd:sequence>
					<xsd:element name="Status" type="rep:TheoreticalTaskStatusType"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="PracticalTaskItemForReportType">
		<xsd:complexContent>
			<xsd:extension base="rep:TaskItemForReportType">
				<xsd:sequence>
					<xsd:element name="Status" type="rep:PracticalTaskStatusType"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="ReportItemType">
		<xsd:sequence>
			<xsd:element name="Tasks">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="Theoretical">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="Task" type="rep:TheoreticalTaskItemForReportType" maxOccurs="unbounded"/>
								</xsd:sequence>
							</xsd:complexType>
							<xsd:unique name="uniqueTheoreticalTaskInReport">
								<xsd:selector xpath="rep:Task"/>
								<xsd:field xpath="@id"/>
							</xsd:unique>
						</xsd:element>
						<xsd:element name="Practical">
							<xsd:complexType>
								<xsd:sequence>
									<xsd:element name="Task" type="rep:PracticalTaskItemForReportType" maxOccurs="unbounded"/>
								</xsd:sequence>
							</xsd:complexType>
							<xsd:unique name="uniquePracticalTaskInReport">
								<xsd:selector xpath="rep:Task"/>
								<xsd:field xpath="@id"/>
							</xsd:unique>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="studentId" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="ReportItemsListType">
		<xsd:sequence>
			<xsd:element name="Report" type="rep:ReportItemType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== n-dobryukha/Curriculum-Viewer/StudentReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<StudentReport
	xmlns="Report"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="Report Report.xsd">
	<Tasks>
		<Task id="1" type="Theoretical">
			<Name>Overview of Eclipse IDE</Name>
			<Duration>4</Duration>
		</Task>
		<Task id="2" type="Theoretical">
			<Name>Learning the Java Language Basics</Name>
			<Duration>12</Duration>
		</Task>
		<Task id="3" type="Practical">
			<Name>Practical Task</Name>
			<Duration>4</Duration>
		</Task>
		<Task id="4" type="Theoretical">
			<Name>Learning the Java Language advanced features</Name>
			<Duration>17</Duration>
		</Task>
		<Task id="5" type="Practical">
			<Name>Practical Task</Name>
			<Duration>16</Duration>
		</Task>
		<Task id="6" type="Theoretical">
			<Name>Learning XML Language</Name>
			<Duration>6</Duration>
		</Task>
		<Task id="7" type="Practical">
			<Name>Practical Task</Name>
			<Duration>8</Duration>
		</Task>
		<Task id="8" type="Theoretical">
			<Name>Learning XSLT and XPath Basics</Name>
			<Duration>14</Duration>
		</Task>
		<Task id="9" type="Practical">
			<Name>Equipment Stylesheets</Name>
			<Duration>8</Duration>
		</Task>
		<Task id="10" type="Theoretical">
			<Name>Struts Framework Fundamentals</Name>
			<Duration>8</Duration>
		</Task>
		<Task id="11" type="Practical">
			<Name>Struts Framework Task</Name>
			<Duration>40</Duration>
		</Task>
		<Task id="12" type="Practical">
			<Name>Java Message Service Task</Name>
			<Duration>20</Duration>
		</Task>
		<Task id="13" type="Theoretical">
			<Name>Mastering Microsoft Project</Name>
			<Duration>3</Duration>
		</Task>
		<Task id="14" type="Practical">
			<Name>MS Project Practical Task</Name>
			<Duration>8</Duration>
		</Task>
		<Task id="15" type="Theoretical">
			<Name>Software development process. Development team and its structure</Name>
			<Duration>12</Duration>
		</Task>
		<Task id="16" type="Practical">
			<Name>Team Project</Name>
			<Duration>80</Duration>
		</Task>
	</Tasks>

	<Courses>
		<Course id="1">
			<Name>Overview of Eclipse IDE</Name>
			<Author>Иванов И.И.</Author>
			<CreationDate>2001-01-01</CreationDate>
			<Tasks>
				<Task id="1" type="Theoretical"/>
			</Tasks>
		</Course>
		<Course id="2">
			<Name>Основы языка Java</Name>
			<Author>Петров П.П.</Author>
			<CreationDate>2002-02-02</CreationDate>
			<Tasks>
				<Task id="2" type="Theoretical"/>
				<Task id="3" type="Practical"/>
			</Tasks>
		</Course>
		<Course id="3">
			<Name>Язык Java - расширенные возможности</Name>
			<Author>Сидоров С.С.</Author>
			<CreationDate>2003-03-03</CreationDate>
			<Tasks>
				<Task id="4" type="Theoretical"/>
				<Task id="5" type="Practical"/>
			</Tasks>
		</Course>
		<Course id="4">
			<Name>Язык XML</Name>
			<Author>Кузнецов К.К.</Author>
			<CreationDate>2004-04-04</CreationDate>
			<Tasks>
				<Task id="6" type="Theoretical"/>
				<Task id="7" type="Practical"/>
			</Tasks>
		</Course>
		<Course id="5">
			<Name>Язык XSLT и XPath</Name>
			<Author>Михайлов М.М.</Author>
			<CreationDate>2005-05-05</CreationDate>
			<Tasks>
				<Task id="8" type="Theoretical"/>
				<Task id="9" type="Practical"/>
			</Tasks>
		</Course>
		<Course id="6">
			<Name>Технология Struts Framework</Name>
			<Author>Никитин Н.Н.</Author>
			<CreationDate>2006-06-06</CreationDate>
			<Tasks>
				<Task id="10" type="Theoretical"/>
				<Task id="11" type="Practical"/>
				<Task id="12" type="Practical"/>
			</Tasks>
		</Course>
		<Course id="7">
			<Name>Процесс производства программного обеспечения</Name>
			<Author>Андреев А.А.</Author>
			<CreationDate>2007-07-07</CreationDate>
			<Tasks>
				<Task id="13" type="Theoretical"/>
				<Task id="14" type="Practical"/>
				<Task id="15" type="Theoretical"/>
			</Tasks>
		</Course>
		<Course id="8">
			<Name>Процесс разработки программного обеспечения</Name>
			<Author>Борисов Б.Б.</Author>
			<CreationDate>2009-09-09</CreationDate>
			<Tasks>
				<Task id="16" type="Practical"/>
			</Tasks>
		</Course>
	</Courses>

	<Programs>
		<Program id="1">
			<Name>Полная программа</Name>
			<Author>Сергеев С.С.</Author>
			<CreationDate>2010-01-01</CreationDate>
			<Courses>
				<Course id="1"/>
				<Course id="2"/>
				<Course id="3"/>
				<Course id="4"/>
				<Course id="5"/>
				<Course id="6"/>
				<Course id="7"/>
				<Course id="8"/>
			</Courses>
		</Program>
		<Program id="2">
			<Name>Укороченная программа</Name>
			<Author>Николаев Н.Н.</Author>
			<CreationDate>2012-02-02</CreationDate>
			<Courses>
				<Course id="1"/>
				<Course id="2"/>
				<Course id="3"/>
				<Course id="7"/>
				<Course id="8"/>
			</Courses>
		</Program>
		<Program id="3">
			<Name>Специальная программа 1</Name>
			<Author>Антонов А.А.</Author>
			<CreationDate>2014-04-04</CreationDate>
			<Courses>
				<Course id="4"/>
				<Course id="5"/>
			</Courses>
		</Program>
	</Programs>

	<Students>
		<Student id="1">
			<FullName>Alexander Sergeev</FullName>
			<City>Moscow</City>
			<Email>a.sergeev@mail.ru</Email>
			<StartDate>2015-04-01</StartDate>
			<IsSigned>false</IsSigned>
			<Program id="1"/>
		</Student>
		<Student id="2">
			<FullName>Boris Romanov</FullName>
			<City>St. Petersburg</City>
			<Email>b.romanov@gmail.com</Email>
			<StartDate>2015-01-15</StartDate>
			<IsSigned>false</IsSigned>
			<Program id="1"/>
		</Student>
		<Student id="3">
			<FullName>Vadim Petrov</FullName>
			<City>Satatov</City>
			<Email>v.petrov@epam.com</Email>
			<StartDate>2014-12-31</StartDate>
			<IsSigned>true</IsSigned>
			<Program id="3"/>
		</Student>
		<Student id="4">
			<FullName>Ivan Fedorov</FullName>
			<City>Engels</City>
			<Email>i.fedorov@epam.com</Email>
			<StartDate>2015-02-01</StartDate>
			<IsSigned>true</IsSigned>
			<Program id="2"/>
		</Student>
	</Students>


	<Reports>
		<Report studentId="1">
			<Tasks>
				<Task id="1" type="Theoretical">
					<Status xsi:type="TheoreticalTaskStatusType">Finished</Status>
				</Task>
				<Task id="2" type="Theoretical">
					<Status xsi:type="TheoreticalTaskStatusType">Finished</Status>
				</Task>
				<Task id="3" type="Practical">
					<Status xsi:type="PracticalTaskStatusType">Accepted</Status>
				</Task>
				<!--<Task id="4" type="Theoretical">
					<Rate>4</Rate>
					<Status>Finished</Status>
				</Task>
				<Task id="5" type="Practical">
					<Rate>4</Rate>
					<Status>Accepted</Status>
				</Task>
				<Task id="6" type="Theoretical">
					<Status>Finished</Status>
				</Task>
				<Task id="7" type="Practical">
					<Status>Verifying</Status>
				</Task>
				<Task id="8" type="Theoretical">
					<Status>In progress</Status>
				</Task>
				<Task id="9" type="Practical">
					<Status>In progress</Status>
				</Task>
				<Task id="10" type="Theoretical">
					<Status>Not started</Status>
				</Task>
				<Task id="11" type="Practical">
					<Status>Not started</Status>
				</Task>
				<Task id="12" type="Practical">
					<Status>Not started</Status>
				</Task>
				<Task id="13" type="Theoretical">
					<Status>Not started</Status>
				</Task>
				<Task id="14" type="Practical">
					<Status>Not started</Status>
				</Task>
				<Task id="15" type="Theoretical">
					<Status>Not started</Status>
				</Task>
				<Task id="16" type="Practical">
					<Status>Not started</Status>
				</Task>-->
			</Tasks>
		</Report>
		<!--
		<Report studentId="2">
			<Tasks>
				<Task id="1" type="Theoretical">
					<Status>Finished</Status>
				</Task>
				<Task id="2" type="Theoretical">
					<Status>Finished</Status>
				</Task>
				<Task id="3" type="Practical">
					<Status>Accepted</Status>
				</Task>
				<Task id="4" type="Theoretical">
					<Rate>4</Rate>
					<Status>Finished</Status>
				</Task>
				<Task id="5" type="Practical">
					<Rate>4</Rate>
					<Status>Accepted</Status>
				</Task>
				<Task id="6" type="Theoretical">
					<Status>Finished</Status>
				</Task>
				<Task id="7" type="Practical">
					<Status>Verifying</Status>
				</Task>
				<Task id="8" type="Theoretical">
					<Status>In progress</Status>
				</Task>
				<Task id="9" type="Practical">
					<Status>In progress</Status>
				</Task>
				<Task id="10" type="Theoretical">
					<Status>Not started</Status>
				</Task>
				<Task id="11" type="Practical">
					<Status>Not started</Status>
				</Task>
				<Task id="12" type="Practical">
					<Status>Not started</Status>
				</Task>
				<Task id="13" type="Theoretical">
					<Status>Not started</Status>
				</Task>
				<Task id="14" type="Practical">
					<Status>Not started</Status>
				</Task>
				<Task id="15" type="Theoretical">
					<Status>Not started</Status>
				</Task>
				<Task id="16" type="Practical">
					<Status>Not started</Status>
				</Task>
			</Tasks>
		</Report>
		<Report studentId="3">
			<Tasks>
				<Task id="5" type="Practical">
					<Rate>5</Rate>
					<Status>Accepted</Status>
				</Task>
				<Task id="6" type="Theoretical">
					<Status>Finished</Status>
				</Task>
				<Task id="8" type="Theoretical">
					<Status>Finished</Status>
				</Task>				
				<Task id="9" type="Practical">
					<Rate>5</Rate>
					<Status>Accepted</Status>
				</Task>
			</Tasks>
		</Report>
		<Report studentId="4">
			<Tasks>
				<Task id="1" type="Theoretical">
					<Status>Finished</Status>
				</Task>
				<Task id="2" type="Theoretical">
					<Status>Finished</Status>
				</Task>
				<Task id="3" type="Practical">
					<Status>Accepted</Status>
				</Task>
				<Task id="4" type="Theoretical">
					<Rate>4</Rate>
					<Status>Finished</Status>
				</Task>
				<Task id="5" type="Practical">
					<Rate>4</Rate>
					<Status>Accepted</Status>
				</Task>
